<script type="text/javascript">
	
	/*filtro */

/* iniciaB1*/

		$(function() {
			load(1);
		});
		function load(page){
var query=$("#NOMBRE_EVENTO").val();
var MENSAJERIA_ENTREGARSOLICITUD=$("#MENSAJERIA_ENTREGARSOLICITUD_1").val();
var MENSAJERIA_FOTOS=$("#MENSAJERIA_FOTOS_1").val();
var MENSAJERIA_FIRMA=$("#MENSAJERIA_FIRMA_1").val();
var MENSAJERIA_FOTOSNECES=$("#MENSAJERIA_FOTOSNECES_1").val();
var MENSAJERIA_ARCHIVORELACIONADO=$("#MENSAJERIA_ARCHIVORELACIONADO_1").val();
var DEPARTAMENTO2=$("#DEPARTAMENTO").val();
var MENSAJERIA_EVENTO=$("#MENSAJERIA_EVENTO_1").val();
var MENSAJERIA_SOLICITUD=$("#MENSAJERIA_SOLICITUD_1").val();
var MENSAJERIA_REALIZARCE=$("#MENSAJERIA_REALIZARCE_1").val();
var MENSAJERIA_HORARIOS=$("#MENSAJERIA_HORARIOS_1").val();
var MENSAJERIA_SOLICITANTE=$("#MENSAJERIA_SOLICITANTE_1").val();
var MENSAJERIA_CEL_SOLICITANTE=$("#MENSAJERIA_CEL_SOLICITANTE_1").val();
var MENSAJERIA_EMPRESA_LUGAR=$("#MENSAJERIA_EMPRESA_LUGAR_1").val();
var MENSAJERIA_SELECCIONAR=$("#MENSAJERIA_SELECCIONAR_1").val();
var MENSAJERIA_OBJETOSARECOJER=$("#MENSAJERIA_OBJETOSARECOJER_1").val();
var MENSAJERIA_MEDIDASAPROX=$("#MENSAJERIA_MEDIDASAPROX_1").val();
var MENSAJERIA_CONTENIDO=$("#MENSAJERIA_CONTENIDO_1").val();
var MENSAJERIA_EMPRESADIRE=$("#MENSAJERIA_EMPRESADIRE_1").val();
var MENSAJERIA_EDIFICIO=$("#MENSAJERIA_EDIFICIO_1").val();
var MENSAJERIA_CALLE=$("#MENSAJERIA_CALLE_1").val();
var MENSAJERIA_NUMEROE=$("#MENSAJERIA_NUMEROE_1").val();
var MENSAJERIA_NINTERIOR=$("#MENSAJERIA_NINTERIOR_1").val();
var MENSAJERIA_NOFICINA=$("#MENSAJERIA_NOFICINA_1").val();
var MENSAJERIA_COLONIA=$("#MENSAJERIA_COLONIA_1").val();
var MENSAJERIA_ALCALDIA=$("#MENSAJERIA_ALCALDIA_1").val();
var MENSAJERIA_CP=$("#MENSAJERIA_CP_1").val();
var MENSAJERIA_CIUDAD=$("#MENSAJERIA_CIUDAD_1").val();
var MENSAJERIA_ESTADO=$("#MENSAJERIA_ESTADO_1").val();
var MENSAJERIA_PAIS=$("#MENSAJERIA_PAIS_1").val();
var MENSAJERIA_UBICACION=$("#MENSAJERIA_UBICACION_1").val();
var MENSAJERIA_TELEFONO1=$("#MENSAJERIA_TELEFONO1_1").val();
var MENSAJERIA_TELEFONO2=$("#MENSAJERIA_TELEFONO2_1").val();
var MENSAJERIA_NOMBREENTREGA=$("#MENSAJERIA_NOMBREENTREGA_1").val();
var MENSAJERIA_FIRMARECIBE=$("#MENSAJERIA_FIRMARECIBE_1").val();
var MENSAJERIA_FECHAR=$("#MENSAJERIA_FECHAR_1").val();
var MENSAJERIA_HORAR=$("#MENSAJERIA_HORAR_1").val();
var MENSAJERIA_LLEVARNOMBRE=$("#MENSAJERIA_LLEVARNOMBRE_1").val();
var MENSAJERIA_SELECCIONARB=$("#MENSAJERIA_SELECCIONARB_1").val();
var MENSAJERIA_DIRECCIONB=$("#MENSAJERIA_DIRECCIONB_1").val();
var MENSAJERIA_EDIFICIOB=$("#MENSAJERIA_EDIFICIOB_1").val();
var MENSAJERIA_CALLEB=$("#MENSAJERIA_CALLEB_1").val();
var MENSAJERIA_NUMEROEB=$("#MENSAJERIA_NUMEROEB_1").val();
var MENSAJERIA_NINTERIORB=$("#MENSAJERIA_NINTERIORB_1").val();
var MENSAJERIA_NOFICINAB=$("#MENSAJERIA_NOFICINAB_1").val();
var MENSAJERIA_COLONIAB=$("#MENSAJERIA_COLONIAB_1").val();
var MENSAJERIA_ALCALDIAB=$("#MENSAJERIA_ALCALDIAB_1").val();
var MENSAJERIA_CPB=$("#MENSAJERIA_CPB_1").val();
var MENSAJERIA_CIUDADB=$("#MENSAJERIA_CIUDADB_1").val();
var MENSAJERIA_ESTADOB=$("#MENSAJERIA_ESTADOB_1").val();
var MENSAJERIA_PAISB=$("#MENSAJERIA_PAISB_1").val();
var MENSAJERIA_UBICACIONB=$("#MENSAJERIA_UBICACIONB_1").val();
var MENSAJERIA_TELEFONO1B=$("#MENSAJERIA_TELEFONO1B_1").val();
var MENSAJERIA_TELEFONO2B=$("#MENSAJERIA_TELEFONO2B_1").val();
var MENSAJERIA_NOMBREPERSONAB=$("#MENSAJERIA_NOMBREPERSONAB_1").val();
var MENSAJERIA_NEMEROCELENTREGA=$("#MENSAJERIA_NEMEROCELENTREGA_1").val();
var MENSAJERIA_NOMBREENTREGAB=$("#MENSAJERIA_NOMBREENTREGAB_1").val();
var MENSAJERIA_FIRMARECIBEB=$("#MENSAJERIA_FIRMARECIBEB_1").val();
var MENSAJERIA_FECHARB=$("#MENSAJERIA_FECHARB_1").val();
var MENSAJERIA_HORARB=$("#MENSAJERIA_HORARB_1").val();
var MENSAJERIA_INSTRUCCIONES=$("#MENSAJERIA_INSTRUCCIONES_1").val();
var MENSAJERIA_OBSERVACIONES=$("#MENSAJERIA_OBSERVACIONES_1").val();
var MENSAJERIA_VEHICULOM=$("#MENSAJERIA_VEHICULOM_1").val();
var MENSAJERIA_REALIZADOPOR=$("#MENSAJERIA_REALIZADOPOR_1").val();
var MENSAJERIA_COSTOCAMIONETA=$("#MENSAJERIA_COSTOCAMIONETA_1").val();
var MENSAJERIA_COSTOGASOLINA=$("#MENSAJERIA_COSTOGASOLINA_1").val();
var MENSAJERIA_COSTOCASETAS=$("#MENSAJERIA_COSTOCASETAS_1").val();
var MENSAJERIA_COSTOESTACIONAMIENTO=$("#MENSAJERIA_COSTOESTACIONAMIENTO_1").val();
var MENSAJERIA_COSTOGASTOS=$("#MENSAJERIA_COSTOGASTOS_1").val();
var MENSAJERIA_TOTAL=$("#MENSAJERIA_TOTAL_1").val();
var MENSAJERIA_OBSERVA=$("#MENSAJERIA_OBSERVA_1").val();
var HMENSAJERIA=$("#HMENSAJERIA_1").val();

/*termina copiar y pegar*/
			
			var per_page=$("#per_pagem").val();
			var parametros = {
			"action":"ajax",
			"page":page,
			'query':query,
			'per_page':per_page,

/*inicia copiar y pegar*/
'MENSAJERIA_EVENTO':MENSAJERIA_EVENTO,
'MENSAJERIA_ENTREGARSOLICITUD':MENSAJERIA_ENTREGARSOLICITUD,
'MENSAJERIA_FOTOS':MENSAJERIA_FOTOS,
'MENSAJERIA_FIRMA':MENSAJERIA_FIRMA,
'MENSAJERIA_FOTOSNECES':MENSAJERIA_FOTOSNECES,
'MENSAJERIA_ARCHIVORELACIONADO':MENSAJERIA_ARCHIVORELACIONADO,
'MENSAJERIA_SOLICITUD':MENSAJERIA_SOLICITUD,
'MENSAJERIA_REALIZARCE':MENSAJERIA_REALIZARCE,
'MENSAJERIA_HORARIOS':MENSAJERIA_HORARIOS,
'MENSAJERIA_SOLICITANTE':MENSAJERIA_SOLICITANTE,
'MENSAJERIA_CEL_SOLICITANTE':MENSAJERIA_CEL_SOLICITANTE,
'MENSAJERIA_EMPRESA_LUGAR':MENSAJERIA_EMPRESA_LUGAR,
'MENSAJERIA_SELECCIONAR':MENSAJERIA_SELECCIONAR,
'MENSAJERIA_OBJETOSARECOJER':MENSAJERIA_OBJETOSARECOJER,
'MENSAJERIA_MEDIDASAPROX':MENSAJERIA_MEDIDASAPROX,
'MENSAJERIA_CONTENIDO':MENSAJERIA_CONTENIDO,
'MENSAJERIA_EMPRESADIRE':MENSAJERIA_EMPRESADIRE,
'MENSAJERIA_EDIFICIO':MENSAJERIA_EDIFICIO,
'MENSAJERIA_CALLE':MENSAJERIA_CALLE,
'MENSAJERIA_NUMEROE':MENSAJERIA_NUMEROE,
'MENSAJERIA_NINTERIOR':MENSAJERIA_NINTERIOR,
'MENSAJERIA_NOFICINA':MENSAJERIA_NOFICINA,
'MENSAJERIA_COLONIA':MENSAJERIA_COLONIA,
'MENSAJERIA_ALCALDIA':MENSAJERIA_ALCALDIA,
'MENSAJERIA_CP':MENSAJERIA_CP,
'MENSAJERIA_CIUDAD':MENSAJERIA_CIUDAD,
'MENSAJERIA_ESTADO':MENSAJERIA_ESTADO,
'MENSAJERIA_PAIS':MENSAJERIA_PAIS,
'MENSAJERIA_UBICACION':MENSAJERIA_UBICACION,
'MENSAJERIA_TELEFONO1':MENSAJERIA_TELEFONO1,
'MENSAJERIA_TELEFONO2':MENSAJERIA_TELEFONO2,
'MENSAJERIA_NOMBREENTREGA':MENSAJERIA_NOMBREENTREGA,
'MENSAJERIA_FIRMARECIBE':MENSAJERIA_FIRMARECIBE,
'MENSAJERIA_FECHAR':MENSAJERIA_FECHAR,
'MENSAJERIA_HORAR':MENSAJERIA_HORAR,
'MENSAJERIA_LLEVARNOMBRE':MENSAJERIA_LLEVARNOMBRE,
'MENSAJERIA_SELECCIONARB':MENSAJERIA_SELECCIONARB,
'MENSAJERIA_DIRECCIONB':MENSAJERIA_DIRECCIONB,
'MENSAJERIA_EDIFICIOB':MENSAJERIA_EDIFICIOB,
'MENSAJERIA_CALLEB':MENSAJERIA_CALLEB,
'MENSAJERIA_NUMEROEB':MENSAJERIA_NUMEROEB,
'MENSAJERIA_NINTERIORB':MENSAJERIA_NINTERIORB,
'MENSAJERIA_NOFICINAB':MENSAJERIA_NOFICINAB,
'MENSAJERIA_COLONIAB':MENSAJERIA_COLONIAB,
'MENSAJERIA_ALCALDIAB':MENSAJERIA_ALCALDIAB,
'MENSAJERIA_CPB':MENSAJERIA_CPB,
'MENSAJERIA_CIUDADB':MENSAJERIA_CIUDADB,
'MENSAJERIA_ESTADOB':MENSAJERIA_ESTADOB,
'MENSAJERIA_PAISB':MENSAJERIA_PAISB,
'MENSAJERIA_UBICACIONB':MENSAJERIA_UBICACIONB,
'MENSAJERIA_TELEFONO1B':MENSAJERIA_TELEFONO1B,
'MENSAJERIA_TELEFONO2B':MENSAJERIA_TELEFONO2B,
'MENSAJERIA_NOMBREPERSONAB':MENSAJERIA_NOMBREPERSONAB,
'MENSAJERIA_NEMEROCELENTREGA':MENSAJERIA_NEMEROCELENTREGA,
'MENSAJERIA_NOMBREENTREGAB':MENSAJERIA_NOMBREENTREGAB,
'MENSAJERIA_FIRMARECIBEB':MENSAJERIA_FIRMARECIBEB,
'MENSAJERIA_FECHARB':MENSAJERIA_FECHARB,
'MENSAJERIA_HORARB':MENSAJERIA_HORARB,
'MENSAJERIA_INSTRUCCIONES':MENSAJERIA_INSTRUCCIONES,
'MENSAJERIA_OBSERVACIONES':MENSAJERIA_OBSERVACIONES,
'MENSAJERIA_VEHICULOM':MENSAJERIA_VEHICULOM,
'MENSAJERIA_REALIZADOPOR':MENSAJERIA_REALIZADOPOR,
'MENSAJERIA_COSTOCAMIONETA':MENSAJERIA_COSTOCAMIONETA,
'MENSAJERIA_COSTOGASOLINA':MENSAJERIA_COSTOGASOLINA,
'MENSAJERIA_COSTOCASETAS':MENSAJERIA_COSTOCASETAS,
'MENSAJERIA_COSTOESTACIONAMIENTO':MENSAJERIA_COSTOESTACIONAMIENTO,
'MENSAJERIA_COSTOGASTOS':MENSAJERIA_COSTOGASTOS,
'MENSAJERIA_TOTAL':MENSAJERIA_TOTAL,
'MENSAJERIA_OBSERVA':MENSAJERIA_OBSERVA,
'HMENSAJERIA':HMENSAJERIA,
/*termina copiar y pegar*/

			'DEPARTAMENTO2':DEPARTAMENTO2
			};
			$("#load").fadeIn('slow');
			$.ajax({
				url:'DIARIO/ClaseMENSAJERIA2/controlador_filtro.php',
				type: 'POST',				
				data: parametros,
				 beforeSend: function(objeto){
				$("#loaderm2").html("Cargando...");
			  },
				success:function(data){
					$(".datos_ajaxM").html(data).fadeIn('slow');
					$("#loaderm2").html("");
				}
			})
		}
/* terminaB1*/		
		
	</script>
